### ISSUE TITLE
I'm curious to see how to save data locally on a device. How would I sync the local changes with mongoDB on the server, either while the device has a strong network signal, or when it gets back on the network?

### ISSUE THREAD

**Issue by dkronquist** [Go-LiveLabs/MEAN-Stack-Series-1#3]

**Comment by pvtech** [comment]
###Steps to implement offline data storage:

 - Check if the connection is online or offline using the following two approaches:
    - navigator.onLine
    - make an ajax call to your server and check if the error if it is not able to connect 
 - use localStorage to save data in a serialized format. To store an object as a key in localStorage, use ``` localStorage.set('car', JSON.stringify({make: 'audi', model: 'a6'})) ``` and to retrieve the object, use ``` JSON.parse(localStorage.get('car')) ```
